/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type CreatedAt = string;
export type UpdatedAt = string;
export type Version = number;
export type IsActive = boolean;
export type CreatedBy = string;
export type FirstName = string;
export type LastName = string;
export type Email = string;
export type PhoneCountryCode =
  | "+44"
  | "+1"
  | "+49"
  | "+33"
  | "+39"
  | "+34"
  | "+31"
  | "+32"
  | "+353"
  | "+45"
  | "+46"
  | "+47"
  | "+358"
  | "+351"
  | "+43"
  | "+41";
export type PhoneNumber = string;
export type DateOfBirth = string;
export type AddressLine1 = string;
export type AddressLine2 = string | null;
export type City = string;
export type Postcode = string;
export type CountryName =
  | "United Kingdom"
  | "United States"
  | "Germany"
  | "France"
  | "Italy"
  | "Spain"
  | "Netherlands"
  | "Belgium"
  | "Ireland"
  | "Denmark"
  | "Sweden"
  | "Norway"
  | "Finland"
  | "Portugal"
  | "Austria"
  | "Switzerland";
export type CountryCode =
  | "GB"
  | "US"
  | "DE"
  | "FR"
  | "IT"
  | "ES"
  | "NL"
  | "BE"
  | "IE"
  | "DK"
  | "SE"
  | "NO"
  | "FI"
  | "PT"
  | "AT"
  | "CH";
export type EmploymentStatus = "EMPLOYED" | "SELF_EMPLOYED" | "UNEMPLOYED";
/**
 * Amount in smallest currency unit (e.g., cents)
 */
export type Amount = number;
export type Currency = "USD" | "GBP" | "EUR";

export interface Client {
  id: Id;
  created_at: CreatedAt;
  updated_at: UpdatedAt;
  version?: Version;
  is_active?: IsActive;
  metadata?: Metadata;
  created_by: CreatedBy;
  first_name: FirstName;
  last_name: LastName;
  email: Email;
  phone_country_code: PhoneCountryCode;
  phone_number: PhoneNumber;
  date_of_birth: DateOfBirth;
  address: Address;
  employment_status: EmploymentStatus;
  annual_income: MonetaryAmount;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
export interface Address {
  address_line_1: AddressLine1;
  address_line_2?: AddressLine2;
  city: City;
  postcode: Postcode;
  country_name: CountryName;
  country_code: CountryCode;
  [k: string]: unknown;
}
/**
 * Amount with currency
 */
export interface MonetaryAmount {
  amount: Amount;
  currency: Currency;
  [k: string]: unknown;
}
