/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type CreatedAt = string;
export type UpdatedAt = string;
export type Version = number;
export type IsActive = boolean;
export type ClientId = string;
export type AnalysisDate = string;
/**
 * Amount in smallest currency unit (e.g., cents)
 */
export type Amount = number;
export type Currency = "USD" | "GBP" | "EUR";
/**
 * Salary stability score between 0 and 1
 */
export type Stability = number | string;
export type ConfidenceScore = number | string;
export type Category = "EXPENSE";
export type TransactionSubcategory =
  | "AUTOMATED_SAVINGS"
  | "BANK_TRANSFER"
  | "SALARY"
  | "REFUND"
  | "PERSONAL_TRANSFER"
  | "FITNESS"
  | "CAR"
  | "PUBLIC"
  | "MICROMOBILITY"
  | "GROCERIES"
  | "TAKEAWAY"
  | "DINING_OUT"
  | "UTILITIES"
  | "RENT"
  | "MORTGAGE"
  | "INSURANCE"
  | "MAINTENANCE"
  | "ONLINE_RETAIL"
  | "IN_STORE_RETAIL"
  | "CLOTHING"
  | "ELECTRONICS"
  | "CASH"
  | "FEES"
  | "SUBSCRIPTIONS"
  | "SOFTWARE"
  | "STREAMING"
  | "ACTIVITIES"
  | "EVENTS"
  | "HOBBIES"
  | "CARE"
  | "EDUCATION"
  | "GIFTS"
  | "OTHER";
/**
 * How often this expense occurs (1.0 = monthly)
 */
export type Frequency = number | string;
export type Confidence = number | string;
export type Breakdown = ExpenseBreakdown[];
export type ExpenseCategories = ExpenseCategory[];
export type ConfidenceScore1 = number | string;
export type RiskFactors1 = "FIXED_COSTS" | "DEBT_TO_INCOME_RATIO" | "INCOME_STABILITY";
export type RiskFactors = RiskFactors1[];
/**
 * Ratio of fixed costs to income
 */
export type FixedCostRatio = number | string;
/**
 * Ratio of debt payments to income
 */
export type DebtToIncomeRatio = number | string;
/**
 * Score indicating income stability
 */
export type IncomeStabilityScore = number | string;
export type RiskLevel = "LOW" | "MEDIUM" | "HIGH";
export type ConfidenceScore2 = number | string;
export type ConfidenceScore3 = number | string;

export interface FinancialAnalysis {
  id: Id;
  created_at: CreatedAt;
  updated_at: UpdatedAt;
  version?: Version;
  is_active?: IsActive;
  metadata?: Metadata;
  client_id: ClientId;
  analysis_date: AnalysisDate;
  income_analysis: IncomeAnalysis;
  expense_analysis: ExpenseAnalysis;
  risk_assessment: RiskAssessment;
  confidence_score?: ConfidenceScore3;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
export interface IncomeAnalysis {
  base_salary: BaseSalary;
  total_monthly_income: MonetaryAmount;
  confidence_score?: ConfidenceScore;
  metadata?: Metadata1;
  [k: string]: unknown;
}
export interface BaseSalary {
  annual: MonetaryAmount;
  monthly: MonetaryAmount;
  stability: Stability;
  [k: string]: unknown;
}
/**
 * Amount with currency
 */
export interface MonetaryAmount {
  amount: Amount;
  currency: Currency;
  [k: string]: unknown;
}
export interface Metadata1 {
  [k: string]: unknown;
}
export interface ExpenseAnalysis {
  fixed_costs: MonetaryAmount;
  expense_categories: ExpenseCategories;
  total_monthly_expenses: MonetaryAmount;
  confidence_score?: ConfidenceScore1;
  metadata?: Metadata3;
  [k: string]: unknown;
}
export interface ExpenseCategory {
  category: Category;
  total: MonetaryAmount;
  breakdown: Breakdown;
  metadata?: Metadata2;
  [k: string]: unknown;
}
export interface ExpenseBreakdown {
  category: TransactionSubcategory;
  amount: MonetaryAmount;
  frequency?: Frequency;
  confidence?: Confidence;
  [k: string]: unknown;
}
export interface Metadata2 {
  [k: string]: unknown;
}
export interface Metadata3 {
  [k: string]: unknown;
}
export interface RiskAssessment {
  risk_factors: RiskFactors;
  risk_metrics: RiskMetrics;
  overall_risk_level: RiskLevel;
  confidence_score?: ConfidenceScore2;
  metadata?: Metadata4;
  [k: string]: unknown;
}
export interface RiskMetrics {
  fixed_cost_ratio: FixedCostRatio;
  debt_to_income_ratio: DebtToIncomeRatio;
  income_stability_score: IncomeStabilityScore;
  [k: string]: unknown;
}
export interface Metadata4 {
  [k: string]: unknown;
}
