/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type ClientId = string;
export type AnalysisDate = string;
export type Amount = number;
export type Currency = "USD" | "GBP" | "EUR";
export type Stability = number | string;
export type Category = "EXPENSE";
export type TransactionSubcategory =
  | "AUTOMATED_SAVINGS"
  | "BANK_TRANSFER"
  | "SALARY"
  | "REFUND"
  | "PERSONAL_TRANSFER"
  | "FITNESS"
  | "CAR"
  | "PUBLIC"
  | "MICROMOBILITY"
  | "GROCERIES"
  | "TAKEAWAY"
  | "DINING_OUT"
  | "UTILITIES"
  | "RENT"
  | "MORTGAGE"
  | "INSURANCE"
  | "MAINTENANCE"
  | "ONLINE_RETAIL"
  | "IN_STORE_RETAIL"
  | "CLOTHING"
  | "ELECTRONICS"
  | "CASH"
  | "FEES"
  | "SUBSCRIPTIONS"
  | "SOFTWARE"
  | "STREAMING"
  | "ACTIVITIES"
  | "EVENTS"
  | "HOBBIES"
  | "CARE"
  | "EDUCATION"
  | "GIFTS"
  | "OTHER";
export type Breakdown = ExpenseBreakdown[];
export type ExpenseCategories = ExpenseCategory[];
export type RiskFactors1 = "FIXED_COSTS" | "DEBT_TO_INCOME_RATIO" | "INCOME_STABILITY";
export type RiskFactors = RiskFactors1[];
export type FixedCostRatio = number | string;
export type DebtToIncomeRatio = number | string;
export type IncomeStabilityScore = number | string;
export type RiskLevel = "LOW" | "MEDIUM" | "HIGH";

export interface FinancialAnalysis {
  id: Id;
  client_id: ClientId;
  analysis_date: AnalysisDate;
  income_analysis: IncomeAnalysis;
  expense_analysis: ExpenseAnalysis;
  risk_assessment: RiskAssessment;
  [k: string]: unknown;
}
export interface IncomeAnalysis {
  base_salary: BaseSalary;
  total_monthly_income: MonetaryAmount;
  [k: string]: unknown;
}
export interface BaseSalary {
  annual: MonetaryAmount;
  monthly: MonetaryAmount;
  stability: Stability;
  [k: string]: unknown;
}
/**
 * Amount with currency
 */
export interface MonetaryAmount {
  amount: Amount;
  currency: Currency;
  [k: string]: unknown;
}
export interface ExpenseAnalysis {
  fixed_costs: MonetaryAmount;
  expense_categories: ExpenseCategories;
  total_monthly_expenses: MonetaryAmount;
  [k: string]: unknown;
}
export interface ExpenseCategory {
  category: Category;
  total: MonetaryAmount;
  breakdown: Breakdown;
  [k: string]: unknown;
}
export interface ExpenseBreakdown {
  category: TransactionSubcategory;
  amount: MonetaryAmount;
  [k: string]: unknown;
}
export interface RiskAssessment {
  risk_factors: RiskFactors;
  risk_metrics: RiskMetrics;
  overall_risk_level: RiskLevel;
  [k: string]: unknown;
}
export interface RiskMetrics {
  fixed_cost_ratio: FixedCostRatio;
  debt_to_income_ratio: DebtToIncomeRatio;
  income_stability_score: IncomeStabilityScore;
  [k: string]: unknown;
}
