/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type CreatedAt = string;
export type UpdatedAt = string;
export type Version = number;
export type IsActive = boolean;
export type Email = string;
export type FirstName = string;
export type LastName = string;
export type AvatarUrl = string | null;
export type AddressLine1 = string;
export type AddressLine2 = string | null;
export type City = string;
export type Postcode = string;
export type CountryName =
  | "United Kingdom"
  | "United States"
  | "Germany"
  | "France"
  | "Italy"
  | "Spain"
  | "Netherlands"
  | "Belgium"
  | "Ireland"
  | "Denmark"
  | "Sweden"
  | "Norway"
  | "Finland"
  | "Portugal"
  | "Austria"
  | "Switzerland";
export type CountryCode =
  | "GB"
  | "US"
  | "DE"
  | "FR"
  | "IT"
  | "ES"
  | "NL"
  | "BE"
  | "IE"
  | "DK"
  | "SE"
  | "NO"
  | "FI"
  | "PT"
  | "AT"
  | "CH";
export type PaymentMethodType = "CREDIT_CARD" | "DEBIT_CARD" | "PAYPAL" | "BANK_TRANSFER";
export type LastFourDigits = string;
export type CardBrand = "VISA" | "MASTERCARD" | "AMERICAN_EXPRESS" | "DISCOVER" | "JCB";
export type ExpirationDate = string;
export type IsDefault = boolean;
export type SubscriptionPlan = "BASIC" | "PREMIUM" | "ENTERPRISE";
export type SubscriptionStatus = "ACTIVE" | "INACTIVE" | "TRIALING" | "CANCELLED";
export type UserType = "CLIENT" | "CO_APPLICANT";

export interface User {
  id: Id;
  created_at: CreatedAt;
  updated_at: UpdatedAt;
  version?: Version;
  is_active?: IsActive;
  metadata?: Metadata;
  email: Email;
  first_name: FirstName;
  last_name: LastName;
  avatar_url?: AvatarUrl;
  address: Address;
  payment_method?: PaymentMethod | null;
  subscription_plan?: SubscriptionPlan | null;
  subscription_status?: SubscriptionStatus | null;
  user_type: UserType;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
export interface Address {
  address_line_1: AddressLine1;
  address_line_2?: AddressLine2;
  city: City;
  postcode: Postcode;
  country_name: CountryName;
  country_code: CountryCode;
  [k: string]: unknown;
}
export interface PaymentMethod {
  type: PaymentMethodType;
  last_four_digits: LastFourDigits;
  card_brand: CardBrand;
  expiration_date: ExpirationDate;
  is_default?: IsDefault;
  billing_address?: Address | null;
  [k: string]: unknown;
}
